server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
